@startuml Chess App


skinparam DefaultFontName Arial
skinparam DefaultFontSize 16
skinparam DefaultFontStyle bold
skinparam ClassBorderColor black
skinparam SequenceMessageAlignment center
skinparam ArrowThickness 1
skinparam ArrowColor #black
hide empty members

skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam TitleFontSize 24

title Chess App



class Game {
    
}

class "Board" as Board {

}

enum PieceType {
    PAWN,
    KNIGHT,
    BISHOP,
    ROCK,
    QUEEN,
    KING;
}

enum Player {
    WHITE,
    BLACK;
}

class Position {
    -x: short;
    -y: short;

    +Position(short x, short y)
    
    +setPosition()
    +getPosition()
}

abstract class Piece {
    -m_player : final Player;
    -m_type : PieceType;
    -m_position : Position;
    
    +Piece()
    
    +abstract bool isValidMove();
    +abstract byte[][] Move();

    +Type getType()
    +Player getPlayer()
}

class Pawn {

}

class Knight {

}

class Bishop {
    
}

class Rock {

}

class Queen {

}

class King {
    
}


Piece <|-- Pawn
Piece <|-- Knight
Piece <|-- Bishop
Piece <|-- Rock
Piece <|-- Queen
Piece <|-- King



@enduml
